Don't sort filenames using LooseVersion.
LooseVersion doesn't work for many special cases of input, and gives very
unhelpful error messages when it breaks. E.g.

  TypeError: '<' not supported between instances of 'int' and 'str'